project 'DZNEmptyDataSetUserForMe.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DZNEmptyDataSetUserForMe' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DZNEmptyDataSetUserForMe

  target 'DZNEmptyDataSetUserForMeTests' do
    inherit! :search_paths
   
    # Pods for testing
  end

  target 'DZNEmptyDataSetUserForMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
